[package]
name = "riscv-rustos"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv = { version = "0.13.0" }
sbi-rt = { version = "0.0.3", features = ["legacy"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
